#!/bin/sh


# check that terraform code was formatted
terraform fmt -recursive -check > /dev/null

if [[ $? -ne 0 ]];
then
    echo "run 'terraform fmt' to format terraform source"
    exit 1
fi

pushd django
# check that django code was formatted
$(pwd)/venv/bin/black --check .
popd
