# Copyright (C) 2022 John DeVries

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.6 on 2021-10-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0003_assignmentsubmission_profile_photo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentsubmission",
            old_name="profile_photo_url",
            new_name="_profile_photo_url",
        ),
    ]
