# Copyright (C) 2022 John DeVries

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.8 on 2021-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0007_gradingsession_ui_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradingsession",
            name="last_synced",
        ),
        migrations.AddField(
            model_name="gradingsession",
            name="sync_state",
            field=models.CharField(
                choices=[("U", "UNSYNCED"), ("S", "SYNCED")], default="U", max_length=2
            ),
        ),
    ]
