# Generated by Django 3.2.8 on 2021-12-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0009_auto_20211205_0526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="grade",
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="gradingsession",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_sessions",
                to="grader.coursemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gradingsession",
            name="max_grade",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
