# Generated by Django 4.0.2 on 2022-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0012_alter_assignmentsubmission_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submission",
            field=models.TextField(default="no attachments found"),
        ),
    ]
