# Generated by Django 4.0.2 on 2022-04-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0013_alter_assignmentsubmission_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentsubmission",
            name="comment",
        ),
    ]
