# Generated by Django 4.0.2 on 2022-04-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0014_remove_assignmentsubmission_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student_name",
            field=models.CharField(blank=True, default="unknown", max_length=200),
        ),
    ]
