# Suitable for development only!!


services:
  web:
    image: jdevries3133/fast_grader_django:${TAG}
    build: .
    ports:
      - "8000:8000"
    entrypoint:
      - sh
      - scripts/entrypoint_dev.sh
    links:
      - db
    volumes:
      - .:/src
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      DJANGO_SECRET: whatever
      DJANGO_DEBUG: "yes indeed"
      DJANGO_SETTINGS_MODULE: fast_grader.settings.development
      DEBUGGING: ${DEBUGGING}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      IS_PRODUCTION: ${IS_PRODUCTION}
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

