# Generated by Django 3.2.6 on 2021-09-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_course_id', models.CharField(max_length=50)),
                ('api_assignment_id', models.CharField(max_length=50)),
                ('max_grade', models.IntegerField()),
                ('teacher_template', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_student_profile_id', models.CharField(max_length=50)),
                ('api_student_submission_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('grade', models.IntegerField(null=True)),
                ('submission', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grader.assignment')),
            ],
        ),
    ]
