# Generated by Django 3.2.6 on 2021-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsession',
            name='max_grade',
            field=models.IntegerField(null=True),
        ),
    ]
