# Generated by Django 3.2.6 on 2021-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_gradingsession_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradingsession',
            name='teacher_template',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
