# Generated by Django 3.2.6 on 2021-10-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_assignmentsubmission_profile_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='profile_photo_url',
            new_name='_profile_photo_url',
        ),
    ]
