# Generated by Django 3.2.6 on 2021-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_auto_20211023_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsession',
            name='last_synced',
            field=models.DateTimeField(null=True),
        ),
    ]
