# Generated by Django 3.2.6 on 2021-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_auto_20210903_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsession',
            name='api_assignment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
