# Generated by Django 3.2.8 on 2021-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0006_gradingsession_last_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingsession",
            name="ui_url",
            field=models.CharField(default="https://classfast.app", max_length=255),
            preserve_default=False,
        ),
    ]
