# Generated by Django 3.2.8 on 2021-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0007_gradingsession_ui_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradingsession",
            name="last_synced",
        ),
        migrations.AddField(
            model_name="gradingsession",
            name="sync_state",
            field=models.CharField(
                choices=[("U", "UNSYNCED"), ("S", "SYNCED")], default="U", max_length=2
            ),
        ),
    ]
