# Generated by Django 3.2.6 on 2021-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_rename_course_coursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingsession',
            name='api_course_id',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='api_course_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
