# Generated by Django 3.2.8 on 2021-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0011_auto_20211207_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="grade",
            field=models.IntegerField(null=True),
        ),
    ]
