# Copyright (C) 2021 John DeVries

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# ---
# This monolithic action does a bunch of things:
#
# - build the django app container
# - run unit tests against the container
# - push the container to docker hub
# - deploy the development infrastructure to minikube
# - run system integration tests against this ephemeral system
# - deploy to staging with terraform


name: CI/CD

on: push

jobs:
  django-deploy:

    name: Test, push, deploy
    runs-on: ubuntu-latest
    environment: Django Deployment
    steps:
    - uses: actions/checkout@v2

    - name: setup Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jdevries3133
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Retrieve Docker layers from cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx

    - name: Setup kubernetes context
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        TEST: ${{ secrets.TEST }}
      run: |
        mkdir ~/.kube
        echo $KUBE_CONFIG > ~/.kube/config
        echo $TEST

    - name: Test, push, and deploy via `make all`
      working-directory: ./django
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: make

    - name: Update cache of Docker layers for next time
      run: |
        rm -rf /tmp/.buildx-cache
        mkdir /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
