# Copyright (C) 2022 John DeVries

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


name: Django App CI/CD

on:
  push:
    branches: ['main']
    paths: [
      "django/**",
      ".github/workflows/django.yml"
    ]

jobs:
  django-deploy:

    name: test, push container, deploy to kubernetes
    runs-on: ubuntu-latest
    environment: Django Deployment
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: jdevries3133
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: run `make all` to test, push container, and then deploy via terraform
      working-directory: ./django
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: |
        mkdir ~/.kube
        echo "${{ secrets.KUBE_CONFIG}}" > ~/.kube/config
        make
