name: Django Tests

on:
  push:
    branches:
      - main
      - containerize
    paths:
      - "django/**"
      - ".github/**"

  pull_request:
    branches: main
    paths:
      - "django/**"
      - ".github/**"

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build the docker image
      working-directory: ./django
      run: docker build . --tag fast_grader
    - name: run tests in image
      run: |
        docker run \
          -e DJANGO_SECRET="foo secret" \
          -e DJANGO_DEBUG=1 \
          -e GOOGLE_CLIENT_ID="any value" \
          -e GOOGLE_CLIENT_SECRET="any value" \
          fast_grader \
          pytest
