# Copyright (C) 2022 John DeVries

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Documentation Website CI/CD 

on:
  push:
    branches: ['main']
    tags: '**'
    paths: [
      "docs/**",
      "Dockerfile.documentation",
      "documentation.tf",
      "mkdocs.yml",
      "requirements.docs.txt",
      ".github/workflows/docs.yml"
    ]

jobs:
  docs-deploy:

    name: deploy docs
    runs-on: ubuntu-latest
    environment: Django Deployment
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jdevries3133
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy docs
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir ~/.kube
        echo "${{ secrets.KUBE_CONFIG}}" > ~/.kube/config
        sh scripts/deploy_static_site.sh
