name: Deploy new documentation

on:
  push:
    branches: ['main']
    paths: [
      "docs/**",
      "Dockerfile.documentation",
      "documentation.tf",
      "mkdocs.yml",
      "requirements.docs.txt",
      ".github/workflows/docs.yml"
    ]

jobs:
  docs-deploy:

    name: Deploy docs
    runs-on: ubuntu-latest
    environment: Django Deployment
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jdevries3133
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy docs
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir ~/.kube
        echo "${{ secrets.KUBE_CONFIG}}" > ~/.kube/config
        sh scripts/deploy_static_site.sh
