name: Test Suites

on:
  push:
    branches: [ main, workflow ]
    paths:
      - '**.py'
      - '**.tsx?'
      - '**.jsx?'
      - '**.json'
      - '**.sh'
      - '**.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.tsx?'
      - '**.jsx?'
      - '**.json'
      - '**.yml'
      - '**.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Dependencies
      run: |
        bash scripts/install_deps.sh
      env:
        CI_CD: true
    - name: Run Tests
      run: |
        bash scripts/test_all.sh
