name: Test Suites

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.tsx?'
      - '**.jsx?'
      - '**.json'
      - '**.sh'
      - '**.yml'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.tsx?'
      - '**.jsx?'
      - '**.json'
      - '**.sh'
      - '**.yml'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      env:
        CI_CD: true
    - name: Run Tests
      run: |
        python3 manage.py test
